package com.stocks.dto

val ASSET_TYPES = listOf("STOCK", "REIT", "ETF", "BDR", "TESOURO_DIRETO", "CRYPTO", "INTERNATIONAL", "RENDA_FIXA", "OUTROS")
val NO_QUOTE_TYPES = setOf("RENDA_FIXA", "OUTROS")
val DIVIDEND_TYPES = listOf("DIVIDENDO", "JCP", "RENDIMENTO", "BONIFICACAO", "BTC")
val VALID_CURRENCIES = listOf("BRL", "USD")
