ALTER TABLE assets ADD COLUMN has_position BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE assets ADD COLUMN quantity DOUBLE NOT NULL DEFAULT 0.0;
ALTER TABLE assets ADD COLUMN avg_price DOUBLE NOT NULL DEFAULT 0.0;
ALTER TABLE assets ADD COLUMN avg_price_brl DOUBLE NOT NULL DEFAULT 0.0;
ALTER TABLE assets ADD COLUMN total_cost DOUBLE NOT NULL DEFAULT 0.0;
ALTER TABLE assets ADD COLUMN total_cost_brl DOUBLE NOT NULL DEFAULT 0.0;
ALTER TABLE assets ADD COLUMN realized_pnl DOUBLE NOT NULL DEFAULT 0.0;
ALTER TABLE assets ADD COLUMN realized_pnl_brl DOUBLE NOT NULL DEFAULT 0.0;
